[package]
name = "corix"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"
num-traits = "0.2.19"

[build-dependencies]
cc = "1.2.30"
bindgen = "0.72.0"

[dev-dependencies]
assert_float_eq = "1.1.4"
